apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: every-hour-backup
  namespace: longhorn-system
spec:
  cron: "0 * * * *"
  task: "backup"
  groups:
  - default
  retain: 1
  concurrency: 1