apiVersion: ENC[AES256_GCM,data:qnw=,iv:lMTH5L2rJRtFM++Sk5jy5QE2DIqmivOTJxYDiWbgsWc=,tag:Ms5n6OH4xJBS1lPNoHzD8A==,type:str]
kind: ENC[AES256_GCM,data:PKNStvHQ,iv:Z2oQ4JF6Wqve+pa2rp52dCSY8XJJoS90rRHjsCq5SXM=,tag:TB56AdijHa0gAFDcyo4S1w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:srFWfO/I/JfFHEcXDLrgfnI=,iv:BwTDRjWODWKhGkROT1iwPRz6G1x+rsWh/663R/Hd9Mg=,tag:1ZdvzD1q/3Yee5QF81b9rw==,type:str]
    namespace: ENC[AES256_GCM,data:WtHrwipLVho41bBppYWU,iv:MriP6HwIqcaKGb/Lzr1YwTwGbFEEVNu4W1G+nuLZUo4=,tag:BkOjex+0YJthHs8yfrKejA==,type:str]
type: ENC[AES256_GCM,data:M+2AR2AN,iv:ZOkiLOsZQxgnvFORkVUw91EzzDzF2qJpHpncQpxndTw=,tag:07nqduTYBr0QaSfs3IoxoQ==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+cO+QzYEvIvsEt4CwHDxKbZFMB8=,iv:VdUysfwVkTaaVaPuGO2+YxOYjMpCqrui8Ajjc6o9SsE=,tag:UIAGzJ/6mwLkt4LtUrOpVw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:IHCh1IEFavOCNYp6patMnzvWnRSEuqjeVnxw7N5PO6lwO8O1n+UsxA==,iv:nVb61R+sCjgLCTM0PcUaSpEpcewwQCOYh+UftJ3qCW4=,tag:oHUXUKg2quACPAjmvdMnpg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:OHs9ig5xN3mhgyjibyUSQnjYv95sYi/7DKq2fFOZTITOwGc=,iv:WyJFxe25emqboeVeUIv+5cbPiVpMxsC8dppeJ8blWgA=,tag:+Iu1+wJdDO+mhJAizT4BMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZWNvSVMrNld5NTBvRStF
            b3VkMkxQelpYcUZ3TUlyNjFrbG9ycytMZGxNCktWVkY1U0ZqWUJLT2lpZHB3bGNj
            aWQvWG5BWVNVYTY1K2YzNjRrVzBpK2cKLS0tIHlyYzJLUEpmZWlIQ0dZNzVIMG9S
            Mjd0ZHdhOFpkbTQ0ZGVtTzlVUWYwdzAKVXEn2/jxwM691n4K/27ZEJGTHox/9D6M
            NS0vff1jOrpATXEJjxByNxBoFcGpyHPL2PKkwi6Ho05BZDkI+prz6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T09:46:40Z"
    mac: ENC[AES256_GCM,data:1ywfyF6+TEg0gNRRCVVP/C2LnVJw5ecr+TrisepVbhBlXG6OfIifVulsPsv+lsHgFX4b/xhDTra12RXPNq949BgS6JPgypkAb/8OEWW8sR7ZSsQnlt4fVKU41pA8sr3vfoZYmEz0jokiN0Ky0PG/ghlLURoBxiJehyNfCNHyg+Y=,iv:ys1R17IsLp9R8ufoBGRfVxVO0TYz1aF9HUeBNzx8bE8=,tag:jyQ7k5M/SeMfp19RqIp9qg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
---
apiVersion: ENC[AES256_GCM,data:AFA=,iv:whaarx9rQ11sScUGYDMaQMxpovUgpOq1K7P7O4wboWE=,tag:6kHWJ4XNuP7lwcuJIpyuLA==,type:str]
kind: ENC[AES256_GCM,data:1A1gyMwC,iv:5eEqrvPcE7s9zp8JX8nMzTcjpD9ezo9k87cnNz50V+8=,tag:94L1t6NSRLrriLfvw627DQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oUC9RZpGYk1tHw==,iv:ILMBVwo4Jv7MMoUbyfwUSC0PLvljY5/qrk+XDJSkH50=,tag:P3K+rNZlEz31/3JPp7iKKA==,type:str]
    namespace: ENC[AES256_GCM,data:qyQbFMvuAHo4IPSTS1xi,iv:vcPH18Ew3hyTp6awcdpdwSvSPjQ2X/2L47RpQS58CRc=,tag:RVbcmLWBsED7Je0rG8Mj1Q==,type:str]
type: ENC[AES256_GCM,data:qVNxG6x3,iv:+k9HmzNXUKNhgTTh9gl+2XP1CbclxyC+TS0ERdbwScU=,tag:DxkBmVpAx8Cota4weq0ZKQ==,type:str]
stringData:
    auth: ENC[AES256_GCM,data:zxj0byOvKY580n6kCGyNdW9ezZ9ypLjE7dC671tYpx/aQUbNbRs736krlOsFtA==,iv:tEkhDgp5SJ6SO4ld9beSn5bkd3Qc97NjlRecf7kdAq0=,tag:RilDYu2wnu0JmAnnYi3FDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZWNvSVMrNld5NTBvRStF
            b3VkMkxQelpYcUZ3TUlyNjFrbG9ycytMZGxNCktWVkY1U0ZqWUJLT2lpZHB3bGNj
            aWQvWG5BWVNVYTY1K2YzNjRrVzBpK2cKLS0tIHlyYzJLUEpmZWlIQ0dZNzVIMG9S
            Mjd0ZHdhOFpkbTQ0ZGVtTzlVUWYwdzAKVXEn2/jxwM691n4K/27ZEJGTHox/9D6M
            NS0vff1jOrpATXEJjxByNxBoFcGpyHPL2PKkwi6Ho05BZDkI+prz6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T09:46:40Z"
    mac: ENC[AES256_GCM,data:1ywfyF6+TEg0gNRRCVVP/C2LnVJw5ecr+TrisepVbhBlXG6OfIifVulsPsv+lsHgFX4b/xhDTra12RXPNq949BgS6JPgypkAb/8OEWW8sR7ZSsQnlt4fVKU41pA8sr3vfoZYmEz0jokiN0Ky0PG/ghlLURoBxiJehyNfCNHyg+Y=,iv:ys1R17IsLp9R8ufoBGRfVxVO0TYz1aF9HUeBNzx8bE8=,tag:jyQ7k5M/SeMfp19RqIp9qg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
