apiVersion: ENC[AES256_GCM,data:1tc=,iv:IL1bW/W7bfjdBljYjtNLFPBLoQM/d7HOWojb3AX07B4=,tag:+XC3jRTFOevlpZLoDoNuiw==,type:str]
kind: ENC[AES256_GCM,data:PzolWYQ2,iv:stm8s2kUEi3HqVNESGPgPUOWRi+mZarOTueKovFFdIY=,tag:zy0o4l9+T22XueWIje5zMQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IeHkj6xP88S9EVFxcO3J1Q==,iv:bA/bgBcC3XGGreXll4/Dl0dw6W2HvTmMj1fhQzTH1L4=,tag:GoTXoXEvKtS81eTB5IhU1Q==,type:str]
    namespace: ENC[AES256_GCM,data:2EulNBHDnI5whTk=,iv:Y/4KcLDYqMzdDaBpI5rZV52ZiS+WzgXjTc2lfiWQouY=,tag:XKaCPJinowjEAJ7WwW/oeQ==,type:str]
type: ENC[AES256_GCM,data:9ZKspO+C,iv:UnLGCxxgm13hNHG1PoMmohC316HsgwO3u938hYkBtKo=,tag:KZCME5QKkASSpnHhO5ijXA==,type:str]
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:3W+eJdM04PIzYtgEOiAndNT1eiz0ROBYkrJLpyGviwwTo92+/70Mb/ZLAx8=,iv:yXNatyQrttSKpv98tLhKVlivkVb/jtOtNvSB+6fVwE4=,tag:In/g3JOaaqNiNGZXramvkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVVQvQ3NzdDZDYk5xUVhX
            aVNiOFk2dis5ZlNjT1pvNEV2Wm9wVlErSnhnCjBNeTdJZTQyQUN1eTl2WjdscWdt
            MUNFKzVuWWpWVzJBSlJNRjRHWGNzYTgKLS0tIE02SUpXK083WE9ZUXVUMGhSWUtu
            Zm5YaE50VlVsODhUWFNTanUyZHRwbkEKsHu6K/7WEg2JlmLlkYribArpPKrJxAMi
            NRdwwT+4F4mfcUYTCMrGrA40GHwhGD8LyTdNGQqjcCI9ebhrLnpj/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T14:35:31Z"
    mac: ENC[AES256_GCM,data:H1HRAI6Y9R2BJg2+OqylgmfomD8Ie8XImryFq6+2NvHYvFOertBhZGss2RcQaL6MQ60cq1nKz/Mq8dPg9TjZ+d+zILurzbpMMC6V/PhJTa9sJkAi1NY/GrxyF834Jh/GG/OOXdE2D6Tmwc51hJwf9FmGIuoDGAsilc47ytpiZmg=,iv:7m7ujed4hFoN2wGnuqAikRk/VcXrsgWahM52VM09pFw=,tag:coT/Wsa+LUCc5rg05Q47WQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
