apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 10m
  chart:
    spec:
      chart: harbor
      version: 1.17.1
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: harbor
      interval: 10m
  values:
    existingSecretAdminPassword: harbor-auth
    existingSecretAdminPasswordKey: harborAdminPassword
    database:
      type: external
      external:
        host: postgresql.postgresql.svc.cluster.local
        port: 5432
        username: harbor
        coreDatabase: registry
        clairDatabase: clair
        notaryServerDatabase: notary_server
        notarySignerDatabase: notary_signer
        existingSecret: harbor-database-auth
    externalURL: "https://harbor.seercle.com"
    expose:
      type: ingress
      ingress:
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          core: "harbor.seercle.com"
    redis:
      enabled: true
    persistence:
      persistentVolumeClaim:
        registry:
          storageClass: longhorn-ssd
        jobservice:
          jobLog:
            storageClass: longhorn-ssd
        redis:
          storageClass: longhorn-ssd
        trivy:
          storageClass: longhorn-ssd
