apiVersion: v1
kind: Secret
metadata:
    name: harbor-registry-auth
    namespace: harbor
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: blocky
data:
    .dockerconfigjson: ENC[AES256_GCM,data:gBodk81+7C00tv64WOahDirP/kdbjeP6DLBarCHzLkzS8GJtTCgRta16TA+3m5GirUPle6Ujzu+tjRz47KXbLSiqHbDJqbQxa6IijFH4vFuwXYd7CgNX/sEGLrmWR+L3AQFvNsak9KRhaq/oqMf60MZo8KyyxLM6KMUCcg==,iv:s9bSNM9cbsQwbpDWKeC/epk71IDa6RdRpIkz5WIgHH4=,tag:XbxQIQUw4P1fo4AnCTTjWA==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreHFFUytkUkZQc3JkM1Vl
            QU00cy8wazNVT25OSjl0bXBpeEtsZ0FINzE4Cng0cExYQkIyNnA5Y21DLzYvY2s1
            c0Y3ZUVpWHlhbmI2SWJGVTltVkR5eWsKLS0tIFlxN0RBOGl5SEsyTnpNVTlDUTdm
            NFB4V0JNSGgrMHAwd2p0aVlJbmM0a0EKGUSgWrh2kKXh0ImQBdNPtaGABdpKoFvE
            rTS7eacBT5GGKNDQStZqBk86j1GWWwvKmun9lPrbfXqzFNgvrlb18Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-07T14:21:08Z"
    mac: ENC[AES256_GCM,data:Hv3xWqSMMbwbk8i9M20pN4Khvh+nvXih9D2xGp7hV26ODSyKfWIWXSkmHhHPSC3oMgpEoTnZYTvftLMzRItL91Knq92KvWljC55i7YdEudaMALdiOJKp+o/FI1CWhuJwNrz4/PTW4wMmJnX/LG8AX5Sb6JOPlmaqFwhytMP5Kao=,iv:SbDBm6l3u/80cnIH7hh4M/ZLfG/hQ1VfYjJSweAtoyU=,tag:FQhB6ZA9ms/t08OWYYTbJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: harbor-auth
    namespace: harbor
type: Opaque
stringData:
    harborAdminPassword: ENC[AES256_GCM,data:rntpdjIDMbmyg5xslCY=,iv:xhjBJr2dtQJD7XEVe+yrSWcIJVfxi0bwHj+d2+ViOx4=,tag:MK/uyjj4cMBo89+q+7hlWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreHFFUytkUkZQc3JkM1Vl
            QU00cy8wazNVT25OSjl0bXBpeEtsZ0FINzE4Cng0cExYQkIyNnA5Y21DLzYvY2s1
            c0Y3ZUVpWHlhbmI2SWJGVTltVkR5eWsKLS0tIFlxN0RBOGl5SEsyTnpNVTlDUTdm
            NFB4V0JNSGgrMHAwd2p0aVlJbmM0a0EKGUSgWrh2kKXh0ImQBdNPtaGABdpKoFvE
            rTS7eacBT5GGKNDQStZqBk86j1GWWwvKmun9lPrbfXqzFNgvrlb18Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-07T14:21:08Z"
    mac: ENC[AES256_GCM,data:Hv3xWqSMMbwbk8i9M20pN4Khvh+nvXih9D2xGp7hV26ODSyKfWIWXSkmHhHPSC3oMgpEoTnZYTvftLMzRItL91Knq92KvWljC55i7YdEudaMALdiOJKp+o/FI1CWhuJwNrz4/PTW4wMmJnX/LG8AX5Sb6JOPlmaqFwhytMP5Kao=,iv:SbDBm6l3u/80cnIH7hh4M/ZLfG/hQ1VfYjJSweAtoyU=,tag:FQhB6ZA9ms/t08OWYYTbJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: harbor-database-auth
    namespace: harbor
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:UjrDZmum5WciRR1PCMHWe6lNjWKSaJXoDvSgdBBqQNjPGDAXSOizAqUeDcs7FW4RjTz6jTXpjiVuiJtPteFkovZ1KFw=,iv:JQLuJvHG4aZJ/b71Qfa+n5oCuZMC1+jWxcfEnwnDFrk=,tag:OS8R5T/B0loVE9+PRxjmMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreHFFUytkUkZQc3JkM1Vl
            QU00cy8wazNVT25OSjl0bXBpeEtsZ0FINzE4Cng0cExYQkIyNnA5Y21DLzYvY2s1
            c0Y3ZUVpWHlhbmI2SWJGVTltVkR5eWsKLS0tIFlxN0RBOGl5SEsyTnpNVTlDUTdm
            NFB4V0JNSGgrMHAwd2p0aVlJbmM0a0EKGUSgWrh2kKXh0ImQBdNPtaGABdpKoFvE
            rTS7eacBT5GGKNDQStZqBk86j1GWWwvKmun9lPrbfXqzFNgvrlb18Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-07T14:21:08Z"
    mac: ENC[AES256_GCM,data:Hv3xWqSMMbwbk8i9M20pN4Khvh+nvXih9D2xGp7hV26ODSyKfWIWXSkmHhHPSC3oMgpEoTnZYTvftLMzRItL91Knq92KvWljC55i7YdEudaMALdiOJKp+o/FI1CWhuJwNrz4/PTW4wMmJnX/LG8AX5Sb6JOPlmaqFwhytMP5Kao=,iv:SbDBm6l3u/80cnIH7hh4M/ZLfG/hQ1VfYjJSweAtoyU=,tag:FQhB6ZA9ms/t08OWYYTbJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
