apiVersion: v1
kind: Secret
metadata:
    name: harbor-auth
    namespace: harbor
type: Opaque
stringData:
    harborAdminPassword: ENC[AES256_GCM,data:JH6bC00PaH0OTapQTAg=,iv:5rEhx8UOtnwhU9Zx+l22VRE89VoLo5NWa+DBShaOle4=,tag:VEB8usuYycNg9lNcdwRpGA==,type:str]
#---
#apiVersion: v1
#kind: Secret
#metadata:
#    name: harbor-registry-auth
#    namespace: harbor
#    annotations:
#        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
#        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
#        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
#        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: capacitor
#type: kubernetes.io/dockerconfigjson
#stringData:
#    .dockerconfigjson: whatever
sops:
    age:
        - recipient: age1vm5gjckxducd5r64sx3m7hm2uwt40xae5d5t7txmp028pgqsc3qsrtytww
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNnhTY21DV3VqZC80eDhj
            eXNSbWlpVW12R1JOd3J5UVpWMFdSU1hZVndFClpBcUh6cVJ0TnVybVRLd1BRQjNa
            aUFabVhJYWd6eWR4emRKZFo1NlBnb2sKLS0tIEJKNUZnRE1hdEdLRnBFMEJnZ00z
            N1lQSlBHUFd0RUxWenlEZCthcVBDWTAKboqhWK2v8lGayjYnpg5kzrfq2cNFh6OZ
            NwRU1iJ9efCIAMbRtkbUmOdrThZQtAsfY0qCcnvBuVCKvKJf2URW5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-15T13:00:40Z"
    mac: ENC[AES256_GCM,data:XtQBv5/v23pt+zVpMJa9d1ZqDONDUIWoCHhkuFtRx3e3wNTOV/Wu1HCyj8pNJAz33LvlNLi6Lc2i6TqxP6ggnuHliH1npryRiR4UZ+s04e3KQuHOPxMP+S/uW/g5SBjS0JENhSJxn7h1E/7G4Wq/IPW4JsBSk8060LW0XHS4tgE=,iv:QxrwomH3KEiAym4e6kib7vRfteysKlB6GacsnCL63F0=,tag:+0auUHfJ34VE+cw9W7p+MA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
