
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: .
    repoURL: git@github.com:seercle/kubernetes.git
    targetRevision: main
    directory:
      recurse: true
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true