apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-system
  namespace: longhorn-system
spec:
  interval: 10m
  chart:
    spec:
      chart: longhorn
      version: 1.9.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-system
        namespace: longhorn-system
      interval: 10m
  values:
    defaultSettings.defaultReplicaCount: 1
    defaultSettings.defaultDataPath: /mnt/sdb1/longhorn
    persistence.defaultClassReplicaCount: 1