apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 10m
  chart:
    spec:
      chart: home-assistant
      version: 0.3.16
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: home-assistant
      interval: 10m
  values:
    ingress:
      external: true
    persistence:
      enabled: true
      storageClass: "longhorn-ssd"
      size: 10Gi
    configuration:
      enabled: true
      forceInit: true
      trusted_proxies:
        - 10.43.0.0/16
