apiVersion: v1
kind: Secret
metadata:
    name: minio-tenant-auth
    namespace: minio
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:QxEWUle7kcBIPNPcGytpGjx0gZA/RTanaYNorR6TCyanEjSuAM5bGHmjbPWYpz2DPsghxvPQSo0xeMcUQExpD9nHnlIIBKJKykYSt6uyGX8VO3JK8iCOsl1ojZUsihl94UiUihMRSGU2anVEtXPAu8oA/Y+53RQeLd2VPSUt,iv:x7dUqcGyUGRcEYhtfiujaT3QmVYF1F9fACc8iTQnX2Y=,tag:E7+d++hGwtZkSCnXevA3oQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbHBSNWZsSHp6a0VKcFNj
            V1pCVW9GQ3VZUnVkNUM2OUhuY3hDd2tsNzFFClRlYmE3MzIvNDN3N0NjVEp2RlQ0
            cGJlSUNPRkdDS2xyNkdnMlVUUGRqYUEKLS0tIEJmcWo5QXRzdjNqVjRDT1FSVVBj
            c1dpSDduNXM3Q0FEd3hmUDZLS2Y4TFUK5SIUVDmXY/R5Irvuow0AuO5ZOauv9yUO
            T0jfSiyuqgaA2SKZ8e2P5Z7PG+/5y5BY+K62lml/RZMOQ1rTYXAddw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-06T13:20:16Z"
    mac: ENC[AES256_GCM,data:bRkI8LbRIojMOkEu7TxUjuR8+dYh9mEiMTlXv2ZJ0F6AK3ffF/FzU1Ffepwd6ylWMnJm3ann9bzA7XRzFtprlecJ9sbA6K8TiVqhttZWlVCYoidAAFcDeC/RuUJY6NXSm93MaIzvhhWf646Q9zKmNsQta+bBp3Ud1jJvnIYSIHc=,iv:r5aB5MR2BUyPGbabXmdNFbwYyVlBWj+BSyOtlSYIVyo=,tag:Xz0pmCno/odubIRq1y0zew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
