apiVersion: v1
kind: Secret
metadata:
    name: longhorn-auth
    namespace: longhorn-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:eZlzz3y71W8mAPOJXciwnNsS5dw=,iv:z9f4yEx+QGKUJ7JiUKAVItpMmm9jY3YBuZ9h0piXMS8=,tag:w2lWExV9q4ui7tfJlFvRAw==,type:comment]
    auth: ENC[AES256_GCM,data:EA982PTgtRHfGpzEld2n3GDVvWrEBaPtc7vBH3VAVpOKoeH3TtP7TizvK7vPhQ==,iv:6srWeLgni8u/pkb4gGgx6xzMOuZ6Va2f0MxppqCB8N8=,tag:W9K4xOUBgZv1B8m2PtTVjQ==,type:str]
sops:
    age:
        - recipient: age1vm5gjckxducd5r64sx3m7hm2uwt40xae5d5t7txmp028pgqsc3qsrtytww
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdURuT1BhZmNJT0lHNDFR
            aE9vOGx3dXhhdGl6bzIzckFZRWkxTVR5dTM4CmRVTlFzNlFWemZJUzlyVkNITFZw
            QmtFd2JLMkZlbXEyUmt5SnZWMHQrbk0KLS0tIEFabnd2VFhMSzJPSG9rZ0tqci84
            UVUxNUxHZ05zd0hvYkJRUjA4VDVMaW8KqD3R5ROwelN5GUdA9vIqnkc2/+Z4ejH2
            MedudzyqwdGVbsLtMVhCUgmifTnE6Qmy6criPiHiP772uoXjMJxxiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T14:28:49Z"
    mac: ENC[AES256_GCM,data:Ak/Rs7giNQ9XYUmKJINsTe2ruxmY8sPBpga3QudlUj0m6Lxrvc2lvvRfxxkiwwR8P0iSiGmzvs2o7x0QY2n3WD6JnWQ5X6zoEjVU0W4Btl7iskq2idBZDA0qGVU/Jfc2+DtJNZFgabeS8e+MwICJb5xD435sbxUAvISgSf3RdNY=,iv:cOuMbmY8YVd2/yysS/siwQv7vuLC0PKjE0WWIQiUEcE=,tag:EY+hLEQj8aY9orPTpMCUeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-auth
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:57YBcF9XYWRm5rSOINQ+Flw+WGA=,iv:o/5u9EE29w5PmZL0E88G5A8QTUZXI4bP83O5i8TgxXs=,tag:vn9ouVnsmD+8SpCfMCTt/A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Os/+lWxkBrhMHalkjHnzkBmhPLxT3LIsUw5Oc3C+x4eziaRSLwd1Ow==,iv:3XAAhR0ynyx91A84iJiLX+7oEby3YW6GmZZciaTDUKI=,tag:80NpFSdvndQUtNX7/s/+jg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:nR3pizeGAydm8i9i/LRqVqM375f19eKYqq2JrW8Y9RMpg+M=,iv:CW6ZS98Ge103PCmtbL2zw8DS/9yjyS6hyo9BBvj/xXw=,tag:afyAliZlRmcWxR98Sz7szA==,type:str]
sops:
    age:
        - recipient: age1vm5gjckxducd5r64sx3m7hm2uwt40xae5d5t7txmp028pgqsc3qsrtytww
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdURuT1BhZmNJT0lHNDFR
            aE9vOGx3dXhhdGl6bzIzckFZRWkxTVR5dTM4CmRVTlFzNlFWemZJUzlyVkNITFZw
            QmtFd2JLMkZlbXEyUmt5SnZWMHQrbk0KLS0tIEFabnd2VFhMSzJPSG9rZ0tqci84
            UVUxNUxHZ05zd0hvYkJRUjA4VDVMaW8KqD3R5ROwelN5GUdA9vIqnkc2/+Z4ejH2
            MedudzyqwdGVbsLtMVhCUgmifTnE6Qmy6criPiHiP772uoXjMJxxiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T14:28:49Z"
    mac: ENC[AES256_GCM,data:Ak/Rs7giNQ9XYUmKJINsTe2ruxmY8sPBpga3QudlUj0m6Lxrvc2lvvRfxxkiwwR8P0iSiGmzvs2o7x0QY2n3WD6JnWQ5X6zoEjVU0W4Btl7iskq2idBZDA0qGVU/Jfc2+DtJNZFgabeS8e+MwICJb5xD435sbxUAvISgSf3RdNY=,iv:cOuMbmY8YVd2/yysS/siwQv7vuLC0PKjE0WWIQiUEcE=,tag:EY+hLEQj8aY9orPTpMCUeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
