apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 10m
  chart:
    spec:
      chart: authentik
      version: 2025.6.4
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      interval: 10m
  values:
    global:
      env:
      - name: AUTHENTIK_POSTGRESQL__HOST
        valueFrom:
          secretKeyRef:
            name: authentik-database-auth
            key: AUTHENTIK_POSTGRESQL__HOST

      - name: AUTHENTIK_POSTGRESQL__NAME
        valueFrom:
          secretKeyRef:
            name: authentik-database-auth
            key: AUTHENTIK_POSTGRESQL__NAME

      - name: AUTHENTIK_POSTGRESQL__USER
        valueFrom:
          secretKeyRef:
            name: authentik-database-auth
            key: AUTHENTIK_POSTGRESQL__USER

      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-database-auth
            key: AUTHENTIK_POSTGRESQL__PASSWORD

      - name: AUTHENTIK_REDIS__HOST
        valueFrom:
          secretKeyRef:
            name: authentik-database-auth
            key: AUTHENTIK_REDIS__HOST

      - name: AUTHENTIK_REDIS__PASSWORD
        valueFrom:
          secretKeyRef:
            name: redis-auth
            key: REDIS_PASSWORD

      - name: AUTHENTIK_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: authentik-auth
            key: AUTHENTIK_SECRET_KEY
    server:
      ingress:
        enabled: false