apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 10m
  chart:
    spec:
      chart: gitlab
      version: 9.2.1
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: gitlab
      interval: 10m
  values:
    global:
      hosts:
        domain: gitlab.seercle.com
      edition: ce
      shell:
        port: 44
      ingress:
        tls:
          external: true
        configureCertmanager: false
        class: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
      psql:
        host: postgresql.postgresql.svc.cluster.local
        port: 5432
        database: gitlab
        username: gitlab
        password:
          secret: gitlab-postgresql-auth
          key: password
    postgresql:
      install: false
    prometheus:
      server:
        persistentVolume:
          storageClass: longhorn-ssd
    gitlab:
      migrations:
        initialRootPassword:
          secret: gitlab-auth
          key: password
      gitaly:
        persistence:
          storageClass: longhorn-ssd
      webservice:
        ingress:
          tls:
            secretName: gitlab-tls
      kas:
        ingress:
          tls:
            secretName: kas-tls
    registry:
      ingress:
        tls:
          secretName: registry-tls
    minio:
      persistence:
        storageClass: longhorn-ssd
      ingress:
        tls:
          secretName: minio-tls
    redis:
      storageClass: longhorn-ssd
    installCertmanager: false
    nginx-ingress:
      enabled: false
