apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-media
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-hdd
  resources:
    requests:
      storage: 2Ti
