apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: servarr
  namespace: servarr
spec:
  interval: 1m
  url: https://charts.kubito.dev
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flaresolverr
  namespace: servarr
spec:
  interval: 1m
  url: https://k8s-home-lab.github.io/helm-charts/
