apiVersion: ENC[AES256_GCM,data:JcY=,iv:0vL/VloxsmEapTnTNH8ygXVLOfZgCW4tw/vqQkX/Vuw=,tag:trkDIsVK9JpU2wd97S9uog==,type:str]
kind: ENC[AES256_GCM,data:ohUqDekE,iv:S9ekH+tBE7M2NO9ZzbnArcK1YgM5YVyWngAWSh/+EbE=,tag:28Rd0lU/Sa2ZpNPuptX3aA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:I5Bq7ek9BjfbdgLHviuUO9La7RiC+Y8=,iv:duJX97ZUK/IaPOyUz1GnjMl/eUztt3P05dTQX+bY7v4=,tag:3tj3513o/UE/H+XLYWLsTA==,type:str]
    namespace: ENC[AES256_GCM,data:dYgVUbwvjb71,iv:cs7mDiLluN9bvu8/RC50tL2r17cuZVUykLGSWsXbRlI=,tag:3Q3KznbjCYNunlBUKwXHYQ==,type:str]
type: ENC[AES256_GCM,data:T1td3yqo,iv:isEIZmzrMC6i4PKLCGiAE27vKIaNZz7zPux957CNvbM=,tag:BlSFsytJdViuYUAz4Z1nYw==,type:str]
stringData:
    NEXTCLOUD_DATABASE_USERNAME: ENC[AES256_GCM,data:pmWnBWawPHzB,iv:GUsYctQ1XiXOgTRnLyMIoa4LuZ6ULU34HcpfGMrr3Qw=,tag:35T56G1Z685qx/DEGsfnrA==,type:str]
    NEXTCLOUD_DATABASE_PASSWORD: ENC[AES256_GCM,data:KBbAXCchvEca17QyniiS98I3NeLyKI81EDPFigDQqQOT69+sGslBHye74Zs=,iv:esAPm+HuzRM8zsJT2hPxwWf2m3yMk8mbRWkvi/7gYIA=,tag:yEbGiu+bzkcrFGkNH3cwtA==,type:str]
    NEXTCLOUD_DATABASE_HOST: ENC[AES256_GCM,data:0e2uRCckM9kpnNE9AMsu47MVnhCB2RwXAr3ZkVbAYWPresIn4/GG,iv:D9ylxMyfbHlsoRmnlX+hn8n2xeTNaTucAB4qq2nFbVM=,tag:tf9dj4eZm3ZMRQ/m2ykIYA==,type:str]
    NEXTCLOUD_DATABASE_NAME: ENC[AES256_GCM,data:9Zhaf77tVicT,iv:qicI8mzSY4nXC6rE45XDkbLsZ7ogixKJrB27Xs0somY=,tag:7/c7YwIQ9vATJb+fO9lcAw==,type:str]
    NEXTCLOUD_ADMIN_USERNAME: ENC[AES256_GCM,data:Pb4rGyY=,iv:hbtBCNdWqwaExFat0RZC5ui9GiFzuOXTbfIlk26gFbk=,tag:GmohCjawHSOc2XjoXjw0JA==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:/P/geFx4fyFXLsYVlz7rhYw9zG4RyBbJ3yTC2gzYH+OZtqrfKcUA8hNv6iK1dPA10k+jaXvqKNekhF8wgFrjOYxZfDA=,iv:JD+2oPsT9cw4nvURsyBINoTmWTpgZgo0uEA30M7wG30=,tag:+K2HnSsjh5CtMuhluNhvvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSERTSUFqVFMzeTJjU1Rj
            MUdkc0JySUQ5QUdMLzBDNXFmR0xhTEpwQUNFCmladUFHWEU5eDRQQkMvU1RCQXpq
            VzA2NEo4dVF0ZHdveXF4a3RydVZLTlkKLS0tIFIxbktPbUQ2MmNESjZzckNyeEhi
            TlQ4OVVhU0NNWkJpblMwRGdXSUlkSUUKbx7OWgK4etEvhimzbbO7Wc19zeatjWxv
            m99q1bqe1JSMQsX6sKMImqoFGE77M1i0o4sI6MyFkw++NTyRL2pikw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T14:58:29Z"
    mac: ENC[AES256_GCM,data:CMkKcQw7iKeD4Q5ZotrSzHZVZq6Mv2NHPifU4s189c0T2gabBGoCpmF3DHu1TdfLcwnU/79giqqv80eV6pSWXRZ1HggkpEwOn3N1riFWJkZfJwDqaatagZQoEzK8EGpNwMdy/3UI1FPa8AiiuAgBE0kb2m0glgAbnVcAp9XQxEM=,iv:ULZOvHVM1mWj45T9pZRr6LZBuKTRTV79XeYhs47y5i4=,tag:rzP4veRYrJY6DVBq/cKpcA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
---
apiVersion: ENC[AES256_GCM,data:JcY=,iv:0vL/VloxsmEapTnTNH8ygXVLOfZgCW4tw/vqQkX/Vuw=,tag:trkDIsVK9JpU2wd97S9uog==,type:str]
kind: ENC[AES256_GCM,data:ohUqDekE,iv:S9ekH+tBE7M2NO9ZzbnArcK1YgM5YVyWngAWSh/+EbE=,tag:28Rd0lU/Sa2ZpNPuptX3aA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Q2HXlc+sCH8vh1x2OAM=,iv:wqwpqfNgpUTtvrln/yXx78Vl2uoyMTTT+UKHxkeNiBw=,tag:xWCLzflz6vQM+puE/habpw==,type:str]
    namespace: ENC[AES256_GCM,data:dYgVUbwvjb71,iv:cs7mDiLluN9bvu8/RC50tL2r17cuZVUykLGSWsXbRlI=,tag:3Q3KznbjCYNunlBUKwXHYQ==,type:str]
type: ENC[AES256_GCM,data:T1td3yqo,iv:isEIZmzrMC6i4PKLCGiAE27vKIaNZz7zPux957CNvbM=,tag:BlSFsytJdViuYUAz4Z1nYw==,type:str]
stringData:
    NEXTCLOUD_ADMIN_USERNAME: ENC[AES256_GCM,data:Pb4rGyY=,iv:hbtBCNdWqwaExFat0RZC5ui9GiFzuOXTbfIlk26gFbk=,tag:GmohCjawHSOc2XjoXjw0JA==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:/P/geFx4fyFXLsYVlz7rhYw9zG4RyBbJ3yTC2gzYH+OZtqrfKcUA8hNv6iK1dPA10k+jaXvqKNekhF8wgFrjOYxZfDA=,iv:JD+2oPsT9cw4nvURsyBINoTmWTpgZgo0uEA30M7wG30=,tag:+K2HnSsjh5CtMuhluNhvvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSERTSUFqVFMzeTJjU1Rj
            MUdkc0JySUQ5QUdMLzBDNXFmR0xhTEpwQUNFCmladUFHWEU5eDRQQkMvU1RCQXpq
            VzA2NEo4dVF0ZHdveXF4a3RydVZLTlkKLS0tIFIxbktPbUQ2MmNESjZzckNyeEhi
            TlQ4OVVhU0NNWkJpblMwRGdXSUlkSUUKbx7OWgK4etEvhimzbbO7Wc19zeatjWxv
            m99q1bqe1JSMQsX6sKMImqoFGE77M1i0o4sI6MyFkw++NTyRL2pikw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T14:58:29Z"
    mac: ENC[AES256_GCM,data:CMkKcQw7iKeD4Q5ZotrSzHZVZq6Mv2NHPifU4s189c0T2gabBGoCpmF3DHu1TdfLcwnU/79giqqv80eV6pSWXRZ1HggkpEwOn3N1riFWJkZfJwDqaatagZQoEzK8EGpNwMdy/3UI1FPa8AiiuAgBE0kb2m0glgAbnVcAp9XQxEM=,iv:ULZOvHVM1mWj45T9pZRr6LZBuKTRTV79XeYhs47y5i4=,tag:rzP4veRYrJY6DVBq/cKpcA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
