apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-database-auth
    namespace: nextcloud
type: Opaque
stringData:
    NEXTCLOUD_DATABASE_USERNAME: ENC[AES256_GCM,data:UC5wZ14U1zuO,iv:6JAPCSNYwB6AEizxdT3gYAQhjBcVrrlPm6/e48NhlOQ=,tag:X6ToM0Vk7QoZ9LDrlVkUnA==,type:str]
    NEXTCLOUD_DATABASE_PASSWORD: ENC[AES256_GCM,data:UIo2pF1Orpn4gMjbNP7qt8xt9RVllMhSkLzlri14aBymcvBC3mPK4WPqHno=,iv:SxlByc6V7Wl3PgZhWiG/ZF+B9r8VEmViKWGY9loc97E=,tag:dMyLt/UaInq1BimBMwe8wQ==,type:str]
    NEXTCLOUD_DATABASE_HOST: ENC[AES256_GCM,data:cw5cM8gkX/7E+HeedytaGyOK7IQ/A9ctm1ahRWMJOgE8LBRTY95F,iv:RrjtGyd2TsAxIynhUdpiIANwErDSmWXn+YFTHf/QdAw=,tag:4e1xgkFHvrvmI3BATnweoA==,type:str]
    NEXTCLOUD_DATABASE_NAME: ENC[AES256_GCM,data:4mgJ18vCsrlE,iv:mcVNu8YNDmPGKxg/KtgTgzoO0pXXTHIHObQ60t96axE=,tag:WT70wCarAyfJv5RQBXKcfg==,type:str]
    NEXTCLOUD_ADMIN_USERNAME: ENC[AES256_GCM,data:KgkJ2HM=,iv:OHwPdVcyTyciSvmMogd3ku1R0TG/MXRbImPJs6t7rb4=,tag:SNVeOio1kNOyZEQq/uMoHg==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:xGyWqteWL8p/kA8+uKyZA6zVYPt1U1uid6xRnyPjZsOYBVoGdmYz71bIvDpXVL1KR/Lj68wUtasd5YD3iMUF0e3mhFg=,iv:JsmbC9t7xwvoX2aXUvtB9kXI/lol/fze2NPiWyz18wc=,tag:MgLcD0KmFwkLn2qfdpM/0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhellVd05XS29qUHB2N3lt
            UHRzWnNZTmtrUE02cUxlQmtlTXR4eE5IVGlBCmtXQ2prNVZZUWZYT2pXa2ZXV2hi
            OU40eE9FdXVIYzNsU2UzZ2JCeEJ4UXcKLS0tIGtGeE81WStYYWhkUnpCTm83Y2wr
            S2JBamdwcFdpQXlkWHJJY3JpNVA1cmcKms97eMHU4B4nBU/tHE+11BZWBvnI9GE8
            huWvkHvEMRDq251PAf33/wm9ufCZlNL17WmHOWAh0OL986nob0G0iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-06T13:20:20Z"
    mac: ENC[AES256_GCM,data:eodTflsG5B/uKOBmDevifth6N540NYQQ/xLb3RrEn3z7tF/0Bpo+OLXVxsnd+0GVTzP7pWzpMowVoYQ9ckx1Ij20wJKq81J+MUkkyGQxahaAozWZ0cg66WF+FY2zQz4EMoVopJpWEDX3hWHQ+WJkKtqg070q2FKRbTRoSm9e4Wg=,iv:/OFok1nR/oyHyeYwXroUaW3mEwAVutGjE7GMbwUOyvo=,tag:WgKrMiraWkkGZ+zTX7K39Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-auth
    namespace: nextcloud
type: Opaque
stringData:
    NEXTCLOUD_ADMIN_USERNAME: ENC[AES256_GCM,data:b1T81mI=,iv:ZbWdNcfdFsPy3Y7qhvvjPF8DlxdkB34qxaJIVHWyni8=,tag:OkNv8YCBd3vdCM8xcEnYqQ==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:xGa7lLN9ZT85VmnM/TFR5UZtkItsvMYZ8KTvnZOmpX4hUKhA22A2+4bNhDsq4E6oSwp8UKdEhJZh2272xDLjh13raXU=,iv:MkCO9W6LVzhSsoyGbGTSG5n/qFKyRfANVrK33r3DbCI=,tag:G8lq3I17AHxMcJpBzJm6sA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhellVd05XS29qUHB2N3lt
            UHRzWnNZTmtrUE02cUxlQmtlTXR4eE5IVGlBCmtXQ2prNVZZUWZYT2pXa2ZXV2hi
            OU40eE9FdXVIYzNsU2UzZ2JCeEJ4UXcKLS0tIGtGeE81WStYYWhkUnpCTm83Y2wr
            S2JBamdwcFdpQXlkWHJJY3JpNVA1cmcKms97eMHU4B4nBU/tHE+11BZWBvnI9GE8
            huWvkHvEMRDq251PAf33/wm9ufCZlNL17WmHOWAh0OL986nob0G0iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-06T13:20:20Z"
    mac: ENC[AES256_GCM,data:eodTflsG5B/uKOBmDevifth6N540NYQQ/xLb3RrEn3z7tF/0Bpo+OLXVxsnd+0GVTzP7pWzpMowVoYQ9ckx1Ij20wJKq81J+MUkkyGQxahaAozWZ0cg66WF+FY2zQz4EMoVopJpWEDX3hWHQ+WJkKtqg070q2FKRbTRoSm9e4Wg=,iv:/OFok1nR/oyHyeYwXroUaW3mEwAVutGjE7GMbwUOyvo=,tag:WgKrMiraWkkGZ+zTX7K39Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
