apiVersion: ENC[AES256_GCM,data:+GY=,iv:i8Zd1bQ8Kgq7tl4N5DsPMQgPBmeSvGUyfAIsFZm9JC0=,tag:f2FIEa1gzLfvs5WQxG3low==,type:str]
kind: ENC[AES256_GCM,data:qrpX+s5m,iv:7bwaHGH0w0bBbG4yuqS49250g4DOC2B5fdOdenv8Lc0=,tag:ql7gLZbcBzxfdWX19jkaiQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kOomY+mDUpg=,iv:4gxDduHSc4XIUEIE+D76XO3HKvO1aUtMamRRHnt6POQ=,tag:iMcRVFq4M6dEXiH5DX1Xrg==,type:str]
    namespace: ENC[AES256_GCM,data:FMHgEkPx,iv:aMp18Y5ZHj0hlxvE9aNrL8lKmCpqPdmFWP8pHGnuVNQ=,tag:Am0au04EAvDa5EauvIofzg==,type:str]
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: ENC[AES256_GCM,data:yurOBA==,iv:JJbPdLva8+JkGxqpz55q2SuUM1UXOq+3DhpGVmBkl8I=,tag:YJW3hNvYi+nYXL/g988ZaQ==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: ENC[AES256_GCM,data:0SKsQw==,iv:5h2IGLy4hISsRpoWV1yrg6bbQwT9Zd2X4rVObeX5o9k=,tag:KnNpjDsvFMOD/14CiCe7Ow==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ENC[AES256_GCM,data:sYc2lH7w,iv:sW1rBe3sBZbqOvU+npVGIIFfB2ew4B1FjaTj66F7OSs=,tag:8KQd3SVJIeqn0lZOQoRkMw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:MnU/CX0gpZjrRBvG8E2yO1eVKt3oDxiFg2fXX6JTLRVu8rpN/6QMRg2T1tWaqQ9QILJPrMA+9EJlvKBjaJdJnY3u8FJr9/gMyHDmIRKUUiV/IacD56Ns9+LMhXA0STIq2Ro0KH5Diup/4Pq/NYEoNsTA1d2Xah3F,iv:8xF2rFuqG3HXeVh38r3eMTspXZ/pu9kCGg5W1xXUgWM=,tag:SSx5QP5wvYoHHLgX7YdVGw==,type:str]
type: ENC[AES256_GCM,data:0MjBYss1F6nEKItO4q01sH152ActTG0E+h3Fj/r/,iv:my2XAQqi9sPeKcx6E+rz0EuOWjHhCwxmjD0q0Y/4z5s=,tag:QDUkCyQ6zCB+Br0NYIB8og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNnB0a1JEc2FOUndwTnpL
            TGZ2UkJvNVdUSnBMcGROUm95Vk1pYTB5UVc4CkhFcWhvL2QvU0tHbjlGTkR4U2Rw
            K2RMc2E2cjFJb21ocDFhdWFUdW8vdTQKLS0tIDJDMk9RQ3Z3OXpKanAvUTl3Slpr
            bFF3cENlVWVlb1Iyc1V5N2ttTSsxeUUKIZKpYcUSCk/9AAHmxCybBUb0sVlAD/9N
            6fJymdx3H7KbpX1WCdPTjEBaH0Pad2ciS54Gjn9VWN+G9sc2nri7HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T09:46:04Z"
    mac: ENC[AES256_GCM,data:LtNZdANivavoYC8Itok1+MHbGOe/hvhgQss8tCF9hPj8iy+0Pp56Qsc7dj444oftH6s6gisiY+4uLx8XCY1rcY9ET+eSEfgEOTNxKfQLnpC2E+6PBo0UYajcMD1fqP5vzetBuSzmsQhKtnFdJFDVspOo41vBwVSHwDZh7yyRUKE=,iv:sLSCmOQv8KGewBVRj0i9GrrbIBwlbVVfW2Gp+7Ei+44=,tag:t9Ap2sIDGe6CcOvDmmRg0Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
---
apiVersion: ENC[AES256_GCM,data:+SI=,iv:USFKgQkLeIKv1MTiLpNCXPu9WAg9MjG5pc9xFQdd5fg=,tag:5m5uqKW1WBJdGjXfjKHb7A==,type:str]
kind: ENC[AES256_GCM,data:9JmKhuBM,iv:77h3KYiOg2Qs/vyqVJy4AlhwnIbBnw9KMG92e4YzqZs=,tag:2LhX4I7W4ryH2zx8lZb5xQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3lslJjYC,iv:K1pSZ745IF5oOrWo1G19X2mN095LTFA82Xk5mPr+8T4=,tag:Mu12oFCn/GJIl7+cLIOOCQ==,type:str]
    namespace: ENC[AES256_GCM,data:bXevi3tJ,iv:c6U0Mq3nAIpOqoD+X5Dxu3X/lR81SmuURnlJ+bDW6EU=,tag:L+WY/YhKQanU8j5i5mexNA==,type:str]
type: ENC[AES256_GCM,data:mnjmDpmq,iv:YGmQuVItEnfpaV/XUzMFtUUDCZPyst5tsUpRSbAFaQU=,tag:H8MKUuFUgY443RsoKdkr1w==,type:str]
stringData:
    values.yaml:
        password:
            harborAdminPassword: ENC[AES256_GCM,data:OH4/bIoVzSmMqk0QSZQ=,iv:hp/hRV12KixFsKzphJtyJ9tbBPSqXjW6wq6pThGCVJg=,tag:yQFmsOh3odJhvlx9FwPmtA==,type:str]
        database:
            type: ENC[AES256_GCM,data:GAJc2Oj9I0I=,iv:V4GjVL08N110U9p1ugNgk3gAZt5DTGaBuYRiaLYrmsw=,tag:IeKCqRf143Odu3LA+0g01g==,type:str]
            external:
                host: ENC[AES256_GCM,data:fHuYKEFKWxJUHSAdfRuAQwvyPqZW/B9ENPalWmn8KuEyQ1mX/Wpn,iv:36UNNu4eZOgCwoxPq7ZLfbfmzbLmCTT6/jvMkkYaMrg=,tag:ldYHkgJ8nLfMmCB+gzXB+g==,type:str]
                port: ENC[AES256_GCM,data:JrEw5Q==,iv:OhpP7bqys/rLQ3bsB2kdyPk4zqslBebrM9Iw0fSxHl0=,tag:DWbbrtiNJGKK2M16xWXW0g==,type:int]
                username: ENC[AES256_GCM,data:kCvI4ZbR,iv:LYqGAAVqnH1ncy/kTYj6TdYTLSRpWxOwQ7gpBfBlgmE=,tag:q8ZeyRYoG4DS884LNWNfFA==,type:str]
                password: ENC[AES256_GCM,data:P2bRNWkRfYXcuOnrV0+DaBc5fvX/IwhLoEeGPU38axctnlRcHxcQbW0bnHd6QDi4456eCfT3Cxo5S6JVr70GD3FqBD4=,iv:g/gOTzlsmzi04JT0lHgBrDN4tZ25+tBRA+1cMtw5xcs=,tag:rKOsvKTvs/vaadPhErLBqw==,type:str]
                coreDatabase: ENC[AES256_GCM,data:UxhoV+SDMjM=,iv:5Tc/6R/JS9kR78Q6AFMqPRHxHUXVG1D/O2LdelxFp1Y=,tag:V0TJStmTDpg4pjG9pLu7GQ==,type:str]
                clairDatabase: ENC[AES256_GCM,data:Cjrz4rI=,iv:iLCQA73zcR9kPFapVNyOPdFuy+XCfCby+24E9Obulgc=,tag:tSwDc3C1vHJyleKxyuIZpA==,type:str]
                notaryServerDatabase: ENC[AES256_GCM,data:bWJNVkJ1jEHUfVvltg==,iv:egDzmUfioXIgAx6t3q3sAT+WGlTmQd0DxN1mI1LOqxM=,tag:Jp6eG+dCUdRkmnMzWHL7Iw==,type:str]
                notarySignerDatabase: ENC[AES256_GCM,data:rqBRv03vMCgxfs1/iw==,iv:HlnhfJqL7gqTF0Je2MOBrE8A8+iXALWFs/2tQpXnIUA=,tag:B7wQJOYiJw/Y5i7M3MmSuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNnB0a1JEc2FOUndwTnpL
            TGZ2UkJvNVdUSnBMcGROUm95Vk1pYTB5UVc4CkhFcWhvL2QvU0tHbjlGTkR4U2Rw
            K2RMc2E2cjFJb21ocDFhdWFUdW8vdTQKLS0tIDJDMk9RQ3Z3OXpKanAvUTl3Slpr
            bFF3cENlVWVlb1Iyc1V5N2ttTSsxeUUKIZKpYcUSCk/9AAHmxCybBUb0sVlAD/9N
            6fJymdx3H7KbpX1WCdPTjEBaH0Pad2ciS54Gjn9VWN+G9sc2nri7HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T09:46:04Z"
    mac: ENC[AES256_GCM,data:LtNZdANivavoYC8Itok1+MHbGOe/hvhgQss8tCF9hPj8iy+0Pp56Qsc7dj444oftH6s6gisiY+4uLx8XCY1rcY9ET+eSEfgEOTNxKfQLnpC2E+6PBo0UYajcMD1fqP5vzetBuSzmsQhKtnFdJFDVspOo41vBwVSHwDZh7yyRUKE=,iv:sLSCmOQv8KGewBVRj0i9GrrbIBwlbVVfW2Gp+7Ei+44=,tag:t9Ap2sIDGe6CcOvDmmRg0Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
