apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-ha
  namespace: redis-ha
spec:
  interval: 10m
  chart:
    spec:
      chart: redis-ha
      version: 4.35.0
      sourceRef:
        kind: HelmRepository
        name: redis-ha
        namespace: redis-ha
      interval: 10m
  values:
    persistentVolume:
      storageClass: longhorn-ssd
    auth: true
    authKey: REDIS_PASSWORD
    existingSecret: redis-ha-auth
    replicas: 1
    sentinel:
      quorum: 1
