apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: git
  namespace: flux-system
spec:
  interval: 1m0s
  url: ssh://git@github.com/seercle/kubernetes
  ref:
    branch: main
  secretRef:
    name: git-auth