---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  #namespace: flux-system
spec:
  interval: 5m
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: git
  path: ./infrastructure
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age