apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sealed-secrets
  namespace: helm-chart
spec:
  repo: https://bitnami-labs.github.io/sealed-secrets
  chart: sealed-secrets
  targetNamespace: sealed-secrets
  createNamespace: true
  valuesContent: |-
    ingress:
      enabled: true
      hostname: sealed-secrets.vivenot.dev
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls: true