apiVersion: v1
kind: Secret
metadata:
    name: gitea-database-auth
    namespace: gitea
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:+uXBdnG1oKg5GUSJkqk=,iv:sAkBeRmxtSA9vc14f2TmWQUPfen7p8+JyLcqh8UOsf4=,tag:5FGgPyVMEyytAXxe3HeRdw==,type:str]
sops:
    age:
        - recipient: age1vm5gjckxducd5r64sx3m7hm2uwt40xae5d5t7txmp028pgqsc3qsrtytww
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Vlk0Q3hxcGd1UFhwOFRX
            NFZZOVVxMEtEWU9TU0NGNGltamg1MWh6c1VjCmxHL2k1aTcwczRSdGFYM3Z1dWRN
            Rm5FZXpyMzZNRnN5Q21ZLzNEOHdvSU0KLS0tIHZyYUlDZ3I4cnYwdU1zUVowZU9U
            M09velZNM1QydFVZMk5vazg1VWtkM28KNrQayJVdOiF3PvuM5Pzl2HPmXOgX8qj8
            wNfqj9jsMqiB0v1gD06Ajc+1e+i1tZlDxBcw1FkcZIKHTJRbejFwLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-18T09:04:33Z"
    mac: ENC[AES256_GCM,data:OJ3sPWhVA5C0J9sDrZmGJbaL5Z9UJ5AGrQYPfeYzDiQWS0tYp3ne66T3D0gudjYYh2oRRCR9UA6p9ZrAMYbLKuPNWgbX52f357AtBaisiTS85Gn1hAENI5imesH2l3QbVUUsIfv4Pnd9JII/stxGSSdwjtEkvsbLNqp0ok4tcL8=,iv:wX63VvWlMR4/lpSzXlcAa7mKaMlArKO20uqMbko1On8=,tag:HBaGOiyQ8Q6DKW700Y1Mqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: gitea-auth
    namespace: gitea
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:aPcTKNE=,iv:BEiqbdBxRcm45TCjGv22fxoCU3bWWb1EfI14koFquuc=,tag:GPenurQqOXjfVksUKE5T4Q==,type:str]
    password: ENC[AES256_GCM,data:SSd1L9gSnseRafrZwrY=,iv:73wc6j+sdrfbf7ZnJyv24ucdMb49RVSmpZUp50MO588=,tag:nao8ze7o83lVhks/HVXBZA==,type:str]
sops:
    age:
        - recipient: age1vm5gjckxducd5r64sx3m7hm2uwt40xae5d5t7txmp028pgqsc3qsrtytww
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Vlk0Q3hxcGd1UFhwOFRX
            NFZZOVVxMEtEWU9TU0NGNGltamg1MWh6c1VjCmxHL2k1aTcwczRSdGFYM3Z1dWRN
            Rm5FZXpyMzZNRnN5Q21ZLzNEOHdvSU0KLS0tIHZyYUlDZ3I4cnYwdU1zUVowZU9U
            M09velZNM1QydFVZMk5vazg1VWtkM28KNrQayJVdOiF3PvuM5Pzl2HPmXOgX8qj8
            wNfqj9jsMqiB0v1gD06Ajc+1e+i1tZlDxBcw1FkcZIKHTJRbejFwLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-18T09:04:33Z"
    mac: ENC[AES256_GCM,data:OJ3sPWhVA5C0J9sDrZmGJbaL5Z9UJ5AGrQYPfeYzDiQWS0tYp3ne66T3D0gudjYYh2oRRCR9UA6p9ZrAMYbLKuPNWgbX52f357AtBaisiTS85Gn1hAENI5imesH2l3QbVUUsIfv4Pnd9JII/stxGSSdwjtEkvsbLNqp0ok4tcL8=,iv:wX63VvWlMR4/lpSzXlcAa7mKaMlArKO20uqMbko1On8=,tag:HBaGOiyQ8Q6DKW700Y1Mqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
