apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: plex
  namespace: servarr
spec:
  interval: 1m
  url: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: servarr
spec:
  interval: 10m
  chart:
    spec:
      chart: plex-media-server
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: servarr
      interval: 10m
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      url: plex.seercle.com
      tls:
        - secretName: plex-tls
          hosts:
            - plex.seercle.com
    pms:
      storageClassName: longhorn-ssd
