apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky
stringData:
  config.yaml: |
    certFile: ./cert.pem
    keyFile: ./key.pem
    upstream:
      groups:
        default:
          - https://one.one.one.one/dns-query
    blocking:
      denylists:
        ads:
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.plus.txt
        adult:
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/nsfw.txt
      clientGroupsBlock:
        default:
          - ads
        kids:
          - ads
          - adult
    caching:
      minTime: 5m
      maxTime: 30m
      prefetching: true