apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocky
  namespace: blocky
spec:
  selector:
    matchLabels:
      app: blocky
  replicas: 1
  template:
    metadata:
      labels:
        app: blocky
    spec:
      containers:
      - image: spx01/blocky:latest
        name: blocky
        volumeMounts:
          - name: app-volume
            mountPath: "/app"
      volumes:
        - name: app-volume
          projected:
            sources:
            - configMap:
                name: blocky
                items:
                  - key: config.yaml
                    path: config.yaml
            - secret:
                name: blocky-tls
                items:
                - key: BLOCKY_CERT_FILE
                  path: cert.pem
                - key: BLOCKY_KEY_FILE
                  path: key.pem
