apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocky
  namespace: blocky
spec:
  selector:
    matchLabels:
      app: blocky
  replicas: 1
  template:
    metadata:
      labels:
        app: blocky
    spec:
      containers:
      - image: spx01/blocky:latest
        name: blocky
        volumeMounts:
          - name: app-config
            mountPath: /app/config.yaml
            subPath: config.yaml
            readOnly: true
          - name: tls-volume
            mountPath: /etc/blocky/tls
            readOnly: true
      volumes:
        - name: app-config
          configMap:
            name: blocky
        - name: tls-volume
          secret:
            secretName: blocky-tls
            items:
            - key: BLOCKY_CERT_FILE
              path: cert.pem
            - key: BLOCKY_KEY_FILE
              path: key.pem
                
