apiVersion: v1
kind: Service
metadata:
  name: blocky
  namespace: blocky
spec:
  type: LoadBalancer
  ports:
  - name: tcp853
    port: 853
    targetPort: 853
    protocol: TCP
  - name: udp53
    port: 53
    targetPort: 53
    protocol: UDP
  - name: tcp53
    port: 53
    targetPort: 53
    protocol: TCP
  selector:
    app: blocky