apiVersion: v1
kind: Secret
metadata:
    name: authentik-auth
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:e8EY4PMiy5c5+w0takshmH1yUEc3bKiRz2ZRHs+ygz2Wwj5/0zQmvL43ceCBQ9WUNkUtWa0Cj4QfRjx6zzeMxCn1DPQ=,iv:z0kXwtBKl8+dhBtcXKNqZUfP099Svp8cJVlUV9aRkUI=,tag:FwzS1NI/17d/HsTXnlhEYQ==,type:str]
sops:
    age:
        - recipient: age1vm5gjckxducd5r64sx3m7hm2uwt40xae5d5t7txmp028pgqsc3qsrtytww
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Vlk0Q3hxcGd1UFhwOFRX
            NFZZOVVxMEtEWU9TU0NGNGltamg1MWh6c1VjCmxHL2k1aTcwczRSdGFYM3Z1dWRN
            Rm5FZXpyMzZNRnN5Q21ZLzNEOHdvSU0KLS0tIHZyYUlDZ3I4cnYwdU1zUVowZU9U
            M09velZNM1QydFVZMk5vazg1VWtkM28KNrQayJVdOiF3PvuM5Pzl2HPmXOgX8qj8
            wNfqj9jsMqiB0v1gD06Ajc+1e+i1tZlDxBcw1FkcZIKHTJRbejFwLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T15:01:14Z"
    mac: ENC[AES256_GCM,data:swA7QA7BBY7PeXYsPWmWz4tw7M8TrOBBKIM0Iyd4WvtLv3riGWURhOGcUMB+7LsAAEokQKplMMh+eaNbGeUupBVftJKOuT8HI04u/6vvh80yJubYMWyv4UCQ/idkRBXXemsuFZepGEKYg/HokwvPbbeWAvxTS7NyJKp5oDHKAvM=,iv:OKQQZjTNAU4JNjus2aeWXY6jWjFvRITLFFBkNu3f19g=,tag:KFalOiUYv+dZnOVJXRnt4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-database-auth
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:HQ/sCovyFnE0ab6LTYxTfgTAx9IENNSFKUD3VCyXUp7Q+JNjs8I=,iv:Mvlwc+A+S+7tWiF5UqXnl8NfHcUyLMBDt/K4k13uIU0=,tag:8rCYR0j+Leeqxf6wz4XpUg==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:QZOhj8BTs+Vb,iv:CTsRG7HYyXLtuIUktAaXlG6qTbnFnw5bcu+nIDnp1x0=,tag:Huluq7KhLGDGnturec8vnw==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:cj3B0iRAcxml,iv:Q2DcnD1isB0u/nnipq1RPTCzUbvTc77gYrLpwBM8N9c=,tag:VWemvZPYQCrMmJNmvALz6g==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:i8EqPoKCIOEukSlm3ylr9Ir9gDXsu7ilXVPlfP7CXNQ4NxoYvJQ9bHRL6S4=,iv:8EB6n/UiA22mv6CqOjtIbjgbyqCOta6JWxDJ3308MWk=,tag:4CgxxX9/18NhTmxZVg3MJQ==,type:str]
    AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:bD3hww9yoqVPC0WcJG2AM30isFValuAQf7lqbmRGVMjDFfk=,iv:2M2/jPgHe9JfXr1UeS4tFEj6uhuBqG0B9eVSyjyS3UE=,tag:1LIVU5hPm7bPHwnMVdZx5A==,type:str]
sops:
    age:
        - recipient: age1vm5gjckxducd5r64sx3m7hm2uwt40xae5d5t7txmp028pgqsc3qsrtytww
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Vlk0Q3hxcGd1UFhwOFRX
            NFZZOVVxMEtEWU9TU0NGNGltamg1MWh6c1VjCmxHL2k1aTcwczRSdGFYM3Z1dWRN
            Rm5FZXpyMzZNRnN5Q21ZLzNEOHdvSU0KLS0tIHZyYUlDZ3I4cnYwdU1zUVowZU9U
            M09velZNM1QydFVZMk5vazg1VWtkM28KNrQayJVdOiF3PvuM5Pzl2HPmXOgX8qj8
            wNfqj9jsMqiB0v1gD06Ajc+1e+i1tZlDxBcw1FkcZIKHTJRbejFwLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T15:01:14Z"
    mac: ENC[AES256_GCM,data:swA7QA7BBY7PeXYsPWmWz4tw7M8TrOBBKIM0Iyd4WvtLv3riGWURhOGcUMB+7LsAAEokQKplMMh+eaNbGeUupBVftJKOuT8HI04u/6vvh80yJubYMWyv4UCQ/idkRBXXemsuFZepGEKYg/HokwvPbbeWAvxTS7NyJKp5oDHKAvM=,iv:OKQQZjTNAU4JNjus2aeWXY6jWjFvRITLFFBkNu3f19g=,tag:KFalOiUYv+dZnOVJXRnt4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
