apiVersion: v1
kind: Secret
metadata:
    name: authentik-auth
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:e8EY4PMiy5c5+w0takshmH1yUEc3bKiRz2ZRHs+ygz2Wwj5/0zQmvL43ceCBQ9WUNkUtWa0Cj4QfRjx6zzeMxCn1DPQ=,iv:z0kXwtBKl8+dhBtcXKNqZUfP099Svp8cJVlUV9aRkUI=,tag:FwzS1NI/17d/HsTXnlhEYQ==,type:str]
sops:
    age:
        - recipient: age1vm5gjckxducd5r64sx3m7hm2uwt40xae5d5t7txmp028pgqsc3qsrtytww
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Vlk0Q3hxcGd1UFhwOFRX
            NFZZOVVxMEtEWU9TU0NGNGltamg1MWh6c1VjCmxHL2k1aTcwczRSdGFYM3Z1dWRN
            Rm5FZXpyMzZNRnN5Q21ZLzNEOHdvSU0KLS0tIHZyYUlDZ3I4cnYwdU1zUVowZU9U
            M09velZNM1QydFVZMk5vazg1VWtkM28KNrQayJVdOiF3PvuM5Pzl2HPmXOgX8qj8
            wNfqj9jsMqiB0v1gD06Ajc+1e+i1tZlDxBcw1FkcZIKHTJRbejFwLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T12:22:37Z"
    mac: ENC[AES256_GCM,data:8FZEYI36GXKSTY9yxnuWvA6qmmU1YyZF81gLRmbZkwoG4myn/9MEtk3cfDqeaPf5LjchbtGYnt8E+ZkL2U5vL92WuWmYqQXuoCLDm5E07LIV9aCDkwvgifkWJN03/Gmu5WwmDi2MQ7PxzDeL6qWh8fA3HzJYkKlBe41nmDU1Krw=,iv:HwifKc3O172i93Pkdlu7h2jrGGIXaVs6dmdnhb/mKLc=,tag:YUzrlfhzv9JFHhMHr22hUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-database-auth
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:1Mq85z0HdlpHixOUuWcbXg==,iv:iXV8dqXUQR6wb+SqxsROxymDDOTdRguawlKouq3heEQ=,tag:bVzZfqaV9nr6FwnDmDnuHw==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:QZOhj8BTs+Vb,iv:CTsRG7HYyXLtuIUktAaXlG6qTbnFnw5bcu+nIDnp1x0=,tag:Huluq7KhLGDGnturec8vnw==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:cj3B0iRAcxml,iv:Q2DcnD1isB0u/nnipq1RPTCzUbvTc77gYrLpwBM8N9c=,tag:VWemvZPYQCrMmJNmvALz6g==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:i8EqPoKCIOEukSlm3ylr9Ir9gDXsu7ilXVPlfP7CXNQ4NxoYvJQ9bHRL6S4=,iv:8EB6n/UiA22mv6CqOjtIbjgbyqCOta6JWxDJ3308MWk=,tag:4CgxxX9/18NhTmxZVg3MJQ==,type:str]
    AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:DK4y7YvF1zLuhWcvMitMW5c=,iv:ioc1A2xjZnjyVuDbVjr0yg4jzWC4fa/sZzygrcaBQII=,tag:XNFaEFJN4nXljwxfLBDBWQ==,type:str]
sops:
    age:
        - recipient: age1vm5gjckxducd5r64sx3m7hm2uwt40xae5d5t7txmp028pgqsc3qsrtytww
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Vlk0Q3hxcGd1UFhwOFRX
            NFZZOVVxMEtEWU9TU0NGNGltamg1MWh6c1VjCmxHL2k1aTcwczRSdGFYM3Z1dWRN
            Rm5FZXpyMzZNRnN5Q21ZLzNEOHdvSU0KLS0tIHZyYUlDZ3I4cnYwdU1zUVowZU9U
            M09velZNM1QydFVZMk5vazg1VWtkM28KNrQayJVdOiF3PvuM5Pzl2HPmXOgX8qj8
            wNfqj9jsMqiB0v1gD06Ajc+1e+i1tZlDxBcw1FkcZIKHTJRbejFwLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T12:22:37Z"
    mac: ENC[AES256_GCM,data:8FZEYI36GXKSTY9yxnuWvA6qmmU1YyZF81gLRmbZkwoG4myn/9MEtk3cfDqeaPf5LjchbtGYnt8E+ZkL2U5vL92WuWmYqQXuoCLDm5E07LIV9aCDkwvgifkWJN03/Gmu5WwmDi2MQ7PxzDeL6qWh8fA3HzJYkKlBe41nmDU1Krw=,iv:HwifKc3O172i93Pkdlu7h2jrGGIXaVs6dmdnhb/mKLc=,tag:YUzrlfhzv9JFHhMHr22hUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
