apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: helm-chart
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetNamespace: argocd
  createNamespace: true
  valuesContent: |-
    global:
      domain: argocd.vivenot.dev
    configs:
      params:
        server.insecure: true
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        extraTls:
          - hosts:
            - argocd.vivenot.dev
            secretName: argocd-tls
    #externalRedis:
    #  existingSecret: argocd-secret
    #  host: redis-master.redis.svc.cluster.local