apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-cluster
  namespace: cnpg
spec:
  chart:
    spec:
      chart: cluster
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg
      interval: 10m
  interval: 10m
  values:
    type: postgresql
    version:
      postgresql: "16"
    mode: standalone
    cluster:
      instances: 1
      enableSuperuserAccess: true
      superuserSecret: "cnpg-superuser"
      storage:
        storageClass: "longhorn-ssd"
      services:
        disabledDefaultServices: ["ro", "r"]
        additional:
          - selectorType: rw
            serviceTemplate:
              metadata:
                name: "cnpg-lb"
                labels:
                  test-label: "true"
                annotations:
                  test-annotation: "true"
              spec:
                type: LoadBalancer
