apiVersion: ENC[AES256_GCM,data:3NI=,iv:Ofi3NulFxeHjvgBjFC1ItCnhLeM/FGnGeBupcVFxMlg=,tag:pLrZmcAGDJQFMh5oMG9E2g==,type:str]
kind: ENC[AES256_GCM,data:VkXdiFvW,iv:iEjQUe1wHCYLQeI1Px0L0KXT7ShvfVjRW+yU+MJmBqU=,tag:exq8IBbias75Isdmcp1XBw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GZLIonmD,iv:XcZ442KXyaj94EBqEd3nG/HKKkO6VhUbM/0jiBNrKMc=,tag:1BRuAx7S8tCmggJW/Z8MDw==,type:str]
    namespace: ENC[AES256_GCM,data:sjUELaFV11QdcA==,iv:FkjrBvEl6Y2zwU7fk+0SdPPAlKk3pc8HkPJ5FX9+ctM=,tag:KGbBuDUWI4N+ImjhHSHV8g==,type:str]
type: ENC[AES256_GCM,data:gJ7pmu4A,iv:x29VFdJ94U4JORKR3kX00uyflhfhfcJZAq51qntrlaM=,tag:2Hv3s+SwtAcalsyNNs8L1g==,type:str]
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:eYlfAj1qL3KdwD+RdamMUOSsuVwUhBWUUwRy5AHQ3kQEsmlF0N/wGvvE++8=,iv:k7RlsLM9pw48S5UXOk/u65cMXwall9dAYTnxrK/T6Bw=,tag:kLfzKoCJL/MCGtJ8TzQqHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeVJpTklVTDY0VHBZNTVP
            ajdHWW0zUzRPOGJGVmYyRXlVWVVKV21VWGtrCm04cWRFd3NzMXFLVVlMYm9RdXlV
            a1RubWhQbC9Jb01CSjF1WFRsZ0ZFUVkKLS0tIGlTWG9nRm1CeXlRZDNHaUhiYmZy
            RytsN3JyeXpXQ09EeHFvNVdEN1d6SFEKzQ/PZOLfhPkxeWuOlJ1Hv19fBvHnvV47
            kJVo75r9sN9HVkg3gBwn7Cd5dedRKV6tFWX8pJh9NzDciMP0WxOpGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T09:47:36Z"
    mac: ENC[AES256_GCM,data:m9k2dxHt490yVtS1sU4Fdp5d4qJd2xheryWImNdAmLabcTeBBqMNRdneo6rd/52kGG69PJ5dHfUtAqeVNFTpkc05nV/bDZ9akOnjrnl5oXvUQhTXo8vghkAXziN3PPA+MHkcaCNoIY9A9Ky5mYh+wyKVOjhxNop3ih1BicRqhXE=,iv:ok+WLq7IthSMOfW7GQTnBAgqCKtsAcdJmMFJpN69d+c=,tag:jc4uA2PYFvWJ8yC3Wy5AmA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
