apiVersion: v1
kind: Secret
metadata:
    name: git-auth
    namespace: flux-system
type: Opaque
stringData:
    identity: ENC[AES256_GCM,data:ASMBiqCDuuzcgCNqmYVWHQxGr9OD7WVmZxr626o+C1sm9HtRR5wuxK+g4KaDCa+/bi4fGt4MJKxHZ98vVWAqrzyVt1h7kcZQpjdY/rxaJ97Lwy685MZtLUZl1nYoCm/G/HuXgZvj8blooKXTvhTItE8HmBZK54BRmfG8tCg1cEzoB+7n7LCBAgDqJgomI9kVrNRy6lkvULbG6Mq3e70C6Ql1wKacoDfnK8eTnVhUnyBeAGVNz6ZDBYQiHyWfrWDgAcNXh2QDZLFhDWWdgbhDqWQMJCvkHzbe0fXqAhnEd8GtGVNNV7FXSheMGQfd3+WjEc45laufFGFeYymkH8qERJN0SctV7fXTG55vcSPhqcqb2JCmmChZFb8abnQ4x8Na0A7S+FtkMSdcg+YS7HaFi1s6rgZ/t06++FwPjqfliUZhAdryWoROnC4WiN8xpWn0Qdyu1mqNP98ik4DSAa7LGEQj6CHB35m6rKZZHI6u/UG7fNSsyYYDYN9kI/NFLp2m0BrfwY60iskbV/NWu7j3,iv:3/nkkpS2UZvruud25uLYnHpSK+V5kyyI+bWO7J+K0F4=,tag:ehzbIrX8DJ5MNDIyeSD2Ng==,type:str]
    known_hosts: ENC[AES256_GCM,data:FK+ojashM7MnmGgeCEVWoaye2XI67+932rdugZAwc+AxGyfk4N7BUYMOY4AEv5yYZxHNaQTJjh3w2v5eecAIa7cm+/G4IhfjWhWko3ikd6SwOXi6TSuOMY8N9KnuYbBMJXXcRsletK5k8/iTOTxEQV5u27+owHAhIlEyylYWVZG2Ip6JZCh7ZJum6Px+uqiJ+zoub4btAMHKt7mcEAf+oMLxqrsX7wDeqWDeqaneRa1Vif2NV8VT5y9rG0f6zC+O6cgTnm3eUGIt5KVFzjwrITZJBVc942yF7XK86BX5x9WLyFBsup8sxEYbi2PxZglO8OEu8RO3YvY6oT2qhw0C8tHcbVui/GT1BcdNiKTfOrDgbJI6ATIw0aKiQhGb5J+nBOPw6+YBO/hzSpT+V3ConhLxMO/PQLmAF66+Fp+mSeBRYdiebVbnYCjvl8vq9K0RNw5Xp5e7IBkZwA6ey91NfdI9WKbSWDwJTuTbGApOd9JyFFUfk+TZiia86kegloQqoMstYtchTfmbwxBTnBwFN+k2TIbV9f54Yn297m1m8Lg9CtwoGBjCpv6GYO6NoBavtqtkuRqgUclcAXTV83/fFYBr6lrIeQBzc2z6ZDH6YBibHisChZX63BqfLewW3tv3JK7k7KN7YQ+eheVR1mcN31AkxWtf13gm3j9hGDaiMf/sHkRBFjO2IYAqAVFOUF88V0tMjIGUIzRlYmJ42qtnXQplb9d8d06hIilApri3k6I51AFc,iv:Fq2ECWOpx3oDA42Ie0B6urqLgulu2llIzpdif0hjf0o=,tag:kNFTUeyjKvss4C/0hFRSJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vm5gjckxducd5r64sx3m7hm2uwt40xae5d5t7txmp028pgqsc3qsrtytww
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbWxrL1NlcHpZVkhyaENr
            b0NsVEU3Z1BTZlU3Rm95MG0zay80cUdUMEhvCmx0UTBNU0pIUmlERDJ0YlZQTC9I
            UFp6Yll3YndrRTVRRUVYUzJ0ZkNUS3cKLS0tIDh6Q2wxeE5xdHlQL294OVlYakFC
            a0VreGwzWlE5RWFieUhWc3Nyc2NDNGcK0igfxHEgNs0g8rmss4pXgJ5y8Fhr50pw
            iVfumWRmnAi6UAjQMd8v/3qRd76C4jcQQL21WuAKGplWsOEyxVkj8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-20T15:24:24Z"
    mac: ENC[AES256_GCM,data:WDyGrQQ5TDhJOrqFfHQrpLfMkl6J1opfoNC1XUilXABPHIvISGgBHrUv0L5nrD6lRDWRcrVjdO7oXUbT/OwJi95+RIYOLOq6rtdI/R4ly7x8oOQ+AV3MVPLcn6LjpdmNG6XkaJieytKVBAlqA1VlEIr0ti8a/tdzmNeZS8EfAys=,iv:8D6vnGYTArLQv8QJAiVx8iAXV3cJOG4yy36eVob2vdY=,tag:r3PgfeckBFC7/A7SSQpfRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
