apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  chartRef:
    kind: OCIRepository
    name: postgresql
    namespace: postgresql
  interval: 10m
  values:
    global:
      postgresql:
        auth:
          existingSecret: postgresql-auth
          secretKeys:
            adminPasswordKey: "ADMIN_PASSWORD"
    primary:
      persistence:
        enabled: true
        storageClass: longhorn-ssd
        size: 5Gi