apiVersion: ENC[AES256_GCM,data:qa4=,iv:Q2/et2TZnbnunVmYjqb/CsgTVkhP4pxrOT7ImVBhixY=,tag:+Gv0LwYDVI8z8sWkb5AnXA==,type:str]
kind: ENC[AES256_GCM,data:x8aJYgzB,iv:ij/Gi2GiQUaI9rU3PesBEXjl0ClCijNAmR2mrccUTB8=,tag:deUbMjxQ4mJhmc/GynVFrQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iYnzBjZwgjUo9g==,iv:LZ5/a2kYljYLuAW08juMglP3XHI1qndzaUXXjVdo2Uw=,tag:RdzteeXeXkTFDcbe0yeiUQ==,type:str]
    namespace: ENC[AES256_GCM,data:Bf0fyHQ=,iv:B2tcoBLcd8m+9esn5SEV5j9mos13j2aPoUPuhcw6pr8=,tag:w8obf7vd3i5dpZgv0107FQ==,type:str]
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: ENC[AES256_GCM,data:Z10F2A==,iv:o05fCGu1HKed7i74qhfQqdaz6+CtjPdaH+3jYPdlb3w=,tag:n5kPehHnzogpagIjVGpMvA==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: ENC[AES256_GCM,data:NHJXgA==,iv:aGXXbMNgymU+g6rcSWmy7M5asjMQ361pYvySVx6oI/s=,tag:9/KozQ92WRUAwJjggpr2sw==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ENC[AES256_GCM,data:keThimbPw8zZOTmqhaVs+w==,iv:S8iEFpfR1C1yuSropQvKRljsCmBZibbUdFyKBt/u2Qo=,tag:Yw4PGef3jkblns+qe9P4+w==,type:str]
type: ENC[AES256_GCM,data:XiaNw1Au,iv:zkYDqarUckttFpfqTAd8jGHICd/Sr6wC8b1wkrtSQFs=,tag:FSwc69j1YWTynmhgLOIheQ==,type:str]
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:UXy2VsAIHIaRz8e2A9xzuQqt1YT1jiv1xd14N5QGkovGjuyKbUQxkXCjNW+2T0s2GJyuiXgvbSzCnD/Qa4/oh4XtAQo=,iv:+RY0OPUxlDB+F9vQJax5QoxePezFsKvPlAhRmRpW0zk=,tag:CpF4FN3l64oI4rtAMrpjiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiU0FweW8vZ1FnOHBycUpX
            b2grV0lVdko0RGZCUUV5VmkxZkV6ejB6SVhJCnBXUUNhSXJ5cVNiTTFoSm0wSnRm
            UEFZYlg3RUhtcEZ0TXNnVmhHQVRieU0KLS0tIDFyWlVMSmdTNGR5SVMxazlYYU56
            QWVqTE1WckdmdnRmdXQ3SHBndVk0b1kKCPfsMTtB7S0Oc6DYc7NCjXv7/uUcJdcG
            kogBcLLyL9p/xAS9fi1o0s0vpKtjiHAjJkmmxIGDwisyd9z8pHVVeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T12:35:45Z"
    mac: ENC[AES256_GCM,data:WJnhy+up8YuzsUcpXU7RdwaDZbC4B5IQDx5iIzgmwpn/WZZiQkNUr2k40AKM7ugegJwpVtdnkChgsnKEOJqGweOf8lYAwxPek1gwJTHlsqIK9D09h4nZONizd1nqDSdJm93+y7WP/rdbegJ0hoLMlXfhtwRM1zq92eAfyU6l0sM=,iv:v7koUKu78OmIIOmfCknp3frY4Zs3E4UGW/Xv/4GGg64=,tag:sRvS7dgQpzXmNmjKDW96ew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
