apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: ingress-nginx
    namespace: ingress-nginx
spec:
    interval: 10m
    chart:
        spec:
            chart: ingress-nginx
            version: 4.13.0
            sourceRef:
                kind: HelmRepository
                name: ingress-nginx
                namespace: ingress-nginx
            interval: 10m
    values:
        tcp:
            "22": "gitea/gitea-ssh:22"
        controller:
            allowSnippetAnnotations: true
            service:
                type: LoadBalancer
                ipFamilies: ["IPv6"]
            config:
                strict-validate-path-type: false
                annotations-risk-level: "Critical"
