apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: github-cluster-secret
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: "github-es"

  # Label selector to select namespaces to deploy ExternalSecrets to
  namespaceSelector:
    matchLabels: {}

  # How often the ClusterExternalSecret should reconcile itself
  refreshTime: "1m"

  # Spec of the ExternalSecrets to be created
  externalSecretSpec:
    secretStoreRef:
      name: github
      kind: ClusterSecretStore

    refreshInterval: "1h"
    target:
      name: github-secret
      creationPolicy: 'Merge'

    dataFrom:
      - key: test_key