apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 1m
  timeout: 1m
  chartRef:
    kind: OCIRepository
    name: redis
    namespace: redis
  values:
    global:
      defaultStorageClass: longhorn-ssd
    auth:
      existingSecret: redis-auth
      existingSecretPasswordKey: REDIS_PASSWORD