---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-services
spec:
  interval: 5m0s
  timeout: 1m0s
  dependsOn:
    - name: apps-database
  sourceRef:
    kind: GitRepository
    name: git
    namespace: flux-system
  path: ./apps/services
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
