---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-post
spec:
  interval: 5m
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: git
    namespace: flux-system
  dependsOn:
    - name: infra-pre
  path: ./infrastructure/post
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age