---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-core
spec:
  interval: 5m
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: git
    namespace: flux-system
  path: ./infrastructure/core
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
