apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    age.agekey: ENC[AES256_GCM,data:i4yRrDnZCB31ct9JMoJdjyXJJQzpCHR81LfzKALpgmkBTFrk9eLD21Rzl31AHsNTvF+QAxlUy/yJ+o0BEga0LGFITEX0JIvHjWI=,iv:RutsS2itcd+h5pcGY2QkoOx3nRS4TpGGW/UYdwXOZJA=,tag:CDICmjmY5prK5k8cplhHWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vm5gjckxducd5r64sx3m7hm2uwt40xae5d5t7txmp028pgqsc3qsrtytww
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WXlUTGdPUVFWNExWR1dR
            Umt4RkNTbkdmQUxWcHJSelYyREF3VXUrQ1JNCmJJaDFaWkZQTTlBd1FCbUkzbWw2
            TUR0VURPTzlQN0llcWQ0QStCWjlhNjgKLS0tIGVmZ3VWMkhsaytOcHdpRUhqZXZX
            bWczQURHTW5EOC8zN0JJdTdYWm5LbncKezSKnF8SLV2DIlUxfepfvPRIWGjE0VCc
            G+SqrSc8CE8TnUfXhxDzSb6PXU30w6pJJU42dahg3W72Q/ti1g3FJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-20T14:56:24Z"
    mac: ENC[AES256_GCM,data:vazO6Wcnxmjx84D619tO9rU6bAdOzAuK8ZthlxV06EsPdStWvnLAWv9VSFVxz+2IcbW8er5gWdKkqpy3b1Nvdjb7LSAR6xXs/yPOohwRuSRilhn8LqcfU5cOuKvKLkNxYqJi6n29HEarPHYm+faKlxopjnraogMhxgLHlOuUghs=,iv:Eeaaq93HlRe1aXXaPhM9KgqWKgfryjBAhh+JYSF2jsk=,tag:BflBAZIO7FzvTrBET2yftA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
