apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: 10.1.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 10m
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - grafana.seercle.com
      tls:
        - hosts:
            - grafana.seercle.com
          secretName: grafana-tls

    admin:
      existingSecret: grafana-auth
      userKey: user
      passwordKey: password

    persistence:
      enabled: true
      storageClassName: longhorn-ssd
